### ISSUE TITLE
Navigation's language

### ISSUE THREAD

**Issue by hugueslacroix** [hugueslacroix/tamaudio#3]
"submit answer": ¿no puede ser en español? si no, se debería poner entre paréntesis arriba.

**Comment by hugueslacroix** [comment]
Sí, @Maura04, puede ser que se me haya olvidado un lugar, ¿me podrías decir dónde exactamente?

**Comment by Maura04** [comment]
Es en la prueba de clasificación, en la parte de "el sueño de Juan Miró"
